spring:
  application:
    name: news-management-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/news_management_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
    username: newsadmin
    password: newspass123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: none  # Flyway manages schema
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  security:
    user:
      name: admin
      password: temporaryPassword  # Will be overridden by database
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: YourVerySecureSecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmShouldBeReplacedInProduction
  expiration: 1800000  # 30 minutes in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

# Crawler Configuration
crawler:
  default-frequency: 4  # hours
  max-concurrent-tasks: 3
  timeout: 30000  # milliseconds
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36

# ZhipuAI Configuration
zhipuai:
  api-url: https://open.bigmodel.cn/api/paas/v4/chat/completions
  api-key: ${ZHIPUAI_API_KEY:key}
  model: glm-4-flash
  timeout: 60000
  max-retries: 3

# Summary Configuration
summary:
  auto-generate: true  # 新闻创建时是否自动生成摘要

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    root: INFO
    com.news: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/news-management.log
    max-size: 10MB
    max-history: 30

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-message: always
    include-binding-errors: always

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  allow-credentials: true
  max-age: 3600

# Application-specific Configuration
app:
  name: News Management System
  version: 1.0.0
  cache:
    news-list-ttl: 300  # 5 minutes in seconds
    category-list-ttl: 3600  # 1 hour in seconds

